In [ ]:
# !pip install numpy
# !pip install matplotlib
# !pip install scikit-learn
# !pip install pandas
# !pip install tdqm

  Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
  Using cached matplotlib-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Using cached contourpy-1.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.55.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (165 kB)
  Using cached kiwisolver-1.4.7-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.3 kB)
  Using cached pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
  Using cached pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Using cached matplotlib-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
Using cached contourpy-1.3.1-cp310-cp310-manylinux_2_17_

In [1]:

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

mnist = datasets.fetch_openml('mnist_784', version=1)
X, y = mnist.data.to_numpy(), mnist.target.astype(int)


1. Tworzymy drzewo z danych (liście to punkty, odległość to ścieżki)
2. robimy radialny rysunek drzewa
3. profit?

In [2]:
print(X.shape)

(70000, 784)


In [2]:
p = np.random.permutation(70000)
radius=np.random.uniform(0.5,1)
print(radius)
moduli=np.sum(X*X,axis=1)
k=2
depth=1
while k<np.sqrt(np.max(moduli)):
    k=k*2
    depth+=1
radius=radius*k
print(k,radius,depth)
#check if dividing by min distance helps results

0.5685005163346442
8192 4657.156229813405 13


In [11]:
from tqdm import tqdm
i=np.log2(radius)
print(i)
# print(np.min(moduli))
# print(moduli)
# print(moduli.shape)

def compute_dists(X, test_X, radius, batch_size=800):
    mindist=radius
    for i in tqdm(range(0, test_X.shape[0], batch_size)):
        batch_X = test_X[i:i + batch_size]
        #this wa we avoid compting  the distanes betweenthhemselves, but the disttances bettwween  thee batch aarere also absent
        print(X[:i].shape)
        print(X[i+batch_size:].shape)
        if i>0:
            train_X=np.vstack([X[:i],X[i+batch_size:]])
        else:
            train_X=X[i+batch_size:]
        print(train_X.shape)
        dists =  np.sqrt(np.sum(train_X**2, axis=1).reshape(1,-1).T + np.sum(batch_X**2,axis=1) - 2*np.dot(train_X, batch_X.T))
        print(dists)
        if np.min(dists)<mindist:
            print(mindist)
            mindist=np.min(dists)

    return mindist

print(compute_dists(X.astype('float32'),X.astype('float32'),radius))

12.185233564543427


  0%|          | 0/88 [00:00<?, ?it/s]

(0, 784)
(69200, 784)
(69200, 784)


  1%|          | 1/88 [00:00<00:45,  1.92it/s]

[[2678.654  2811.8044 2723.5308 ... 2355.3916 2222.1194 2521.6042]
 [3029.9346 2926.011  2506.2893 ... 2641.7236 2841.655  3023.7947]
 [2474.894  2865.4968 2615.399  ... 2345.435  2421.5435 2455.519 ]
 ...
 [2627.5635 2928.5857 2678.8157 ... 1402.847  2460.8274 2599.0483]
 [2693.4753 2660.976  2808.1008 ... 2598.2217 2596.2024 2591.0022]
 [2944.14   2512.646  3202.1177 ... 2892.1833 3161.2996 2866.3816]]
4657.156229813405
(800, 784)
(68400, 784)
(69200, 784)


  2%|▏         | 2/88 [00:01<00:43,  1.99it/s]

[[2678.654  3029.9346 2474.894  ... 2648.1704 2440.3865 2164.231 ]
 [2811.8044 2926.011  2865.4968 ... 2833.2905 2570.076  2493.7117]
 [2723.5308 2506.2893 2615.399  ... 2463.5261 2665.1228 2707.5137]
 ...
 [2067.3552 2499.5627 2105.9834 ... 2170.9138 2504.7607 2392.2378]
 [2679.0576 2668.7249 2558.755  ... 2406.8804 2570.921  2529.4695]
 [2872.6636 2926.9412 2482.7004 ... 3117.3894 2990.8513 3158.1677]]
279.26154
(1600, 784)
(67600, 784)
(69200, 784)


  3%|▎         | 3/88 [00:01<00:41,  2.04it/s]

[[2339.8186 2631.4094 2909.119  ... 2668.6726 2341.0042 3059.5164]
 [2676.857  2832.608  3110.6414 ... 2354.0974 2599.4385 3117.4395]
 [2468.093  2578.277  3065.613  ... 2866.76   2031.47   2916.2346]
 ...
 [2647.8147 2432.192  2790.1858 ... 2784.0493 2161.9404 2908.9365]
 [2671.8474 2486.2266 2983.12   ... 2541.3188 2564.7566 3011.8975]
 [2860.0344 3121.9275 3215.2004 ... 1889.7389 2890.234  2878.7664]]
(2400, 784)
(66800, 784)
(69200, 784)


  5%|▍         | 4/88 [00:01<00:40,  2.06it/s]

[[2842.0288 2714.59   2030.0615 ... 2413.4167 2630.5483 2775.734 ]
 [3144.0203 2711.4387 2532.019  ... 2666.498  2107.9958 2868.074 ]
 [3159.0674 2580.0916 2463.7703 ... 2571.2712 3315.3342 2639.2512]
 ...
 [2587.6287 2386.555  2286.074  ... 2485.1572 3302.9878 2302.4116]
 [2582.7788 2058.691  2518.2883 ... 2386.493  3052.3838 2496.4333]
 [3134.147  3087.041  2874.963  ... 3019.025  2805.8228 2718.5054]]
268.07462
(3200, 784)
(66000, 784)
(69200, 784)


  6%|▌         | 5/88 [00:02<00:40,  2.06it/s]

[[2834.0347 2529.9668 2538.0198 ... 2672.9634 2685.2888 2693.4248]
 [3002.2031 2539.0112 2994.5403 ... 2868.6462 2748.4119 2756.2737]
 [2860.8142 2706.491  2403.3357 ... 2880.544  2225.4524 2676.7634]
 ...
 [3039.9453 2714.2468 2549.5693 ... 2677.1528 2494.641  2579.0146]
 [2845.9617 2465.1758 2553.3264 ... 2888.8003 2930.1655 2950.517 ]
 [3331.4187 2991.7217 3221.9568 ... 3186.533  2659.4111 2198.7896]]
(4000, 784)
(65200, 784)
(69200, 784)


  7%|▋         | 6/88 [00:02<00:39,  2.09it/s]

[[2298.688  2563.3628 2806.41   ... 3058.0942 2612.4502 3230.8594]
 [2796.9656 2721.7    1727.677  ... 3050.95   2759.5286 2800.6204]
 [2756.424  2726.3867 3310.764  ... 2815.3333 2319.9973 2485.0178]
 ...
 [2140.5574 2675.404  3213.3906 ... 3053.3992 2037.2501 3188.1353]
 [2641.2163 2698.791  2985.6733 ... 3359.2036 2421.084  3192.5217]
 [3117.499  3043.1807 2480.078  ... 3182.0647 2910.8381 3240.537 ]]
(4800, 784)
(64400, 784)
(69200, 784)


  8%|▊         | 7/88 [00:03<00:40,  2.02it/s]

[[2693.5056 2838.2236 2666.1023 ... 2456.088  2306.692  2463.0352]
 [2674.3728 3215.7102 2848.9148 ... 2547.209  2569.9197 2499.6907]
 [2445.6206 3011.3267 2423.829  ... 2904.4834 2864.1206 2704.1443]
 ...
 [2542.125  2780.2576 2233.5007 ... 2291.054  2250.73   2410.6216]
 [2509.6533 3395.686  2613.3481 ... 2285.4587 2335.4912 1972.8578]
 [2648.1028 3172.5125 2883.649  ... 3120.493  2905.6204 2909.0125]]
(5600, 784)
(63600, 784)
(69200, 784)


  9%|▉         | 8/88 [00:03<00:39,  2.05it/s]

[[2370.192  2458.4468 2335.4133 ... 2641.1477 2492.1575 2481.1587]
 [2946.6846 2739.3503 2740.3538 ... 2613.9417 2748.528  2479.12  ]
 [2463.1233 2592.536  2430.3435 ... 2848.491  2571.4465 3043.6665]
 ...
 [2430.388  2303.479  2413.0808 ... 2397.4404 2526.8145 2639.0176]
 [2453.6443 2421.3772 2365.7095 ... 2575.6624 2340.69   2852.4001]
 [2703.5466 3109.87   2770.1443 ... 2953.4602 3061.4714 2334.8572]]
(6400, 784)
(62800, 784)
(69200, 784)


 10%|█         | 9/88 [00:04<00:38,  2.05it/s]

[[2889.6765 2205.9128 2463.6555 ... 2383.4075 2580.074  2448.9673]
 [2234.0188 2386.8813 2538.1313 ... 2522.1667 2865.7544 2667.098 ]
 [3063.6155 3139.9175 2836.9382 ... 2466.145  2210.5596 2545.4106]
 ...
 [3071.529  2684.938  2726.2104 ... 2006.535  2698.9053 2377.658 ]
 [3162.2866 2859.8777 2456.229  ... 2204.5356 2979.04   2345.3188]
 [3033.8435 2620.3774 2170.7466 ... 2894.6995 3087.0425 2903.7065]]
(7200, 784)
(62000, 784)
(69200, 784)


 11%|█▏        | 10/88 [00:04<00:38,  2.05it/s]

[[2360.9429 2275.306  2968.9297 ... 2727.7686 2124.6453 3175.5945]
 [2764.131  2457.2947 3061.672  ... 2892.8306 2678.9863 3047.5864]
 [2711.5337 2424.9294 2762.4016 ... 2911.1504 2368.2803 2226.8918]
 ...
 [2084.1355 1859.9589 2956.4648 ... 2715.6272 2415.7153 3123.794 ]
 [2276.9666 2284.2932 2981.32   ... 2975.9236 2845.8066 3150.403 ]
 [3060.598  2812.8198 2814.317  ... 2354.2632 3041.5986 3144.496 ]]
(8000, 784)
(61200, 784)
(69200, 784)


 12%|█▎        | 11/88 [00:05<00:37,  2.06it/s]

[[2805.7844 2923.697  2947.3052 ... 2512.9912 2393.863  2661.082 ]
 [2001.7598 2999.5886 3124.3003 ... 2893.128  2739.397  2941.6416]
 [3124.0557 3056.935  2716.5615 ... 2716.2866 2751.3916 2687.9868]
 ...
 [3040.66   2952.1445 2653.6812 ... 2587.1934 1918.87   2482.7998]
 [3068.1228 3196.605  2629.446  ... 2195.7998 2337.0588 2260.8506]
 [2378.563  2369.6865 2914.5618 ... 2716.5945 3117.583  2857.1438]]
(8800, 784)
(60400, 784)
(69200, 784)


 14%|█▎        | 12/88 [00:05<00:36,  2.07it/s]

[[2332.126  2267.799  2431.4526 ... 2673.2603 2523.344  2314.1533]
 [2709.0903 2485.8955 2684.8545 ... 2739.9817 2789.9827 2768.9082]
 [2520.9622 2526.032  2447.1155 ... 2387.647  2547.8083 2566.432 ]
 ...
 [2503.8342 2037.4349 1752.254  ... 2691.3057 2572.7415 2527.769 ]
 [2448.973  2471.512  2476.63   ... 2865.2231 2661.1343 2160.0269]
 [3071.5374 2956.287  2941.2483 ... 2852.612  2901.6628 2896.843 ]]
(9600, 784)
(59600, 784)
(69200, 784)


 15%|█▍        | 13/88 [00:06<00:36,  2.07it/s]

[[2925.2505 2717.2087 2466.2795 ... 2699.7078 2324.1392 2423.6135]
 [3232.0845 2707.8381 3037.0962 ... 2815.7104 2564.8433 2683.763 ]
 [3105.6145 2574.934  2915.7083 ... 3170.5588 2601.3447 2742.2632]
 ...
 [2857.6382 2152.3425 2289.6792 ... 3007.2087 2160.3145 2261.2378]
 [2835.0242 2252.966  2456.6443 ... 3400.8167 2429.0767 2270.6418]
 [2790.2908 2816.4097 3204.7764 ... 3206.2505 2866.7175 3014.4324]]
(10400, 784)
(58800, 784)
(69200, 784)


 16%|█▌        | 14/88 [00:06<00:35,  2.06it/s]

[[2777.651  2444.2373 2529.0286 ... 2225.278  2337.4158 2348.6753]
 [2995.6016 2434.0542 3012.501  ... 2860.7954 2531.7246 2663.8057]
 [2506.4597 2925.9993 2547.2832 ... 2763.247  2786.6108 2583.3752]
 ...
 [2481.974  2918.1313 2486.4143 ... 2703.7703 2431.9604 1549.0875]
 [2810.1538 2867.982  2841.3733 ... 2814.0132 1966.989  2259.2432]
 [3058.5798 2833.452  3282.2625 ... 3300.7148 3080.779  2919.0251]]
(11200, 784)
(58000, 784)
(69200, 784)


 17%|█▋        | 15/88 [00:07<00:35,  2.04it/s]

[[2359.9824 2271.423  2749.5864 ... 2952.0725 3172.535  2434.0325]
 [2648.5186 2917.7703 2880.626  ... 2948.964  3225.0286 2769.2292]
 [2478.2957 2705.9077 2681.1765 ... 3318.1963 3385.7625 3107.3123]
 ...
 [2528.4805 2650.9722 2727.329  ... 3044.8071 2769.3235 2445.328 ]
 [2234.4868 2816.3374 3206.6418 ... 3325.5935 2901.3958 2803.0745]
 [2888.4988 3332.013  3448.8682 ... 2935.7585 3169.1863 3183.1082]]
(12000, 784)
(57200, 784)
(69200, 784)


 18%|█▊        | 16/88 [00:07<00:34,  2.06it/s]

[[2477.2053 2905.1296 2302.3948 ... 2976.6272 2381.532  2636.9521]
 [2854.818  2999.1582 2720.8245 ... 2745.562  2711.1482 2344.6707]
 [2652.3447 2487.1838 2361.0742 ... 2413.4438 2672.2825 2599.3604]
 ...
 [2292.0515 2170.1377 2151.8044 ... 2711.561  2445.921  2659.6426]
 [2829.2083 2539.2751 2505.3494 ... 2689.644  2228.187  2703.7695]
 [3230.1328 3135.321  2635.294  ... 2790.7258 2857.13   2504.4968]]
(12800, 784)
(56400, 784)
(69200, 784)


 19%|█▉        | 17/88 [00:08<00:34,  2.08it/s]

[[2907.047  2418.662  2396.926  ... 2633.9622 2450.778  2491.235 ]
 [2938.738  2782.0798 2876.6118 ... 2703.5605 2634.1907 2618.5767]
 [2891.8528 2480.2722 2878.0066 ... 2985.4553 2376.2615 2791.7424]
 ...
 [2967.3242 2293.686  2562.131  ... 2355.6582 2422.3594 2317.0288]
 [3280.0342 2515.08   2683.124  ... 2525.1912 2500.1067 2590.0576]
 [3130.3518 2389.056  2827.128  ... 2989.118  2539.5522 3170.3123]]
(13600, 784)
(55600, 784)
(69200, 784)


 20%|██        | 18/88 [00:08<00:33,  2.10it/s]

[[2644.0015 2479.6426 2746.239  ... 2839.6497 2721.1624 2460.772 ]
 [2901.7954 2473.4087 2741.2952 ... 2884.733  2983.2622 2834.4402]
 [2722.0437 3174.3523 2428.7937 ... 2503.8687 2857.5247 2771.8728]
 ...
 [2676.2239 2932.8042 2689.802  ... 2058.2998 2637.1965 2579.1846]
 [2841.8772 2875.8872 2750.3608 ... 2436.9214 2806.1104 2275.3262]
 [3344.1636 3025.2463 3205.4387 ... 2880.936  3190.8804 2464.482 ]]
(14400, 784)
(54800, 784)
(69200, 784)


 22%|██▏       | 19/88 [00:09<00:32,  2.12it/s]

[[2784.785  2447.4136 2582.5637 ... 2610.3813 3040.9255 2755.6   ]
 [2773.0293 2881.0413 1580.701  ... 2668.4163 2461.879  2738.2974]
 [2666.5964 2772.0024 3015.108  ... 2485.3079 3138.8376 2238.5347]
 ...
 [2465.9624 2604.7097 2808.1858 ... 2444.7195 3308.353  2606.5217]
 [2814.751  2877.7786 2703.1248 ... 1547.4893 3196.5684 2512.816 ]
 [2506.9944 3261.4258 2332.0872 ... 2901.4387 2808.3035 3206.9592]]
(15200, 784)
(54000, 784)
(69200, 784)


 23%|██▎       | 20/88 [00:09<00:32,  2.11it/s]

[[2676.285  2403.4941 2343.1382 ... 2391.9778 2522.2878 2312.8384]
 [2887.2012 2795.4832 2790.0886 ... 2676.2463 2904.342  2614.1567]
 [2318.5088 2426.7217 2653.5718 ... 2845.715  2693.043  2675.7441]
 ...
 [2769.2827 2489.1025 2375.2046 ... 2099.0442 2047.053  2232.9722]
 [2728.213  2821.9358 2419.3071 ... 2466.8381 2395.3508 2296.0132]
 [3250.5964 3191.6255 3104.779  ... 3054.6765 3321.8071 3005.792 ]]
(16000, 784)
(53200, 784)
(69200, 784)


 24%|██▍       | 21/88 [00:10<00:32,  2.07it/s]

[[2492.7627 2644.162  2191.3513 ... 2639.6553 2599.5723 2481.64  ]
 [2711.9097 3115.2324 2581.454  ... 2661.341  2904.1768 2786.1147]
 [3077.2302 3174.911  2453.479  ... 2391.0842 2710.645  2476.568 ]
 ...
 [2207.474  3098.6487 2586.3237 ... 2411.5332 2532.8813 2525.5273]
 [2387.9824 2810.489  2096.783  ... 2023.158  2641.7146 2364.85  ]
 [3047.4966 2883.7913 2742.1128 ... 2986.9656 3182.9358 3094.7761]]
(16800, 784)
(52400, 784)
(69200, 784)


 25%|██▌       | 22/88 [00:10<00:31,  2.09it/s]

[[2759.1797 2405.1458 2947.688  ... 2542.124  2376.0603 2388.4287]
 [2899.8372 2587.9077 3051.9546 ... 2605.65   2551.4788 2598.1816]
 [2427.1836 2294.5679 2138.5923 ... 2326.6296 2434.8577 2446.4187]
 ...
 [2650.0693 1692.2878 2909.7358 ... 2335.9155 2362.8054 2401.3184]
 [2535.5083 2380.4646 3050.872  ... 2608.5127 2781.567  2320.1914]
 [3213.8672 2970.6326 3106.0007 ... 2879.0747 2815.4324 2969.3347]]
(17600, 784)
(51600, 784)
(69200, 784)


 26%|██▌       | 23/88 [00:11<00:30,  2.10it/s]

[[2851.1865 2765.524  3140.2769 ... 2340.8066 2695.2832 2456.6423]
 [2940.1882 2527.331  3364.236  ... 2529.7598 3084.122  2409.365 ]
 [3152.9907 2800.7773 3516.5244 ... 2756.3345 2651.1008 2658.8591]
 ...
 [2912.6829 2755.6746 2904.0085 ... 2705.6504 2784.6746 2288.6892]
 [2835.8328 2881.087  3004.2153 ... 2363.5913 2814.9502 2639.4995]
 [2895.0771 2085.4856 3226.2324 ... 2746.647  3144.4934 2898.537 ]]
(18400, 784)
(50800, 784)
(69200, 784)


 27%|██▋       | 24/88 [00:11<00:30,  2.11it/s]

[[2310.617  2548.0974 3000.687  ... 2713.1003 2478.5056 2238.7239]
 [2705.1619 2797.844  3133.065  ... 2489.7734 2877.3887 2571.8362]
 [2421.318  2685.146  2647.7512 ... 2733.711  1989.8502 2493.8357]
 ...
 [2401.377  2353.2673 3001.183  ... 2595.9458 2556.7913 2278.3315]
 [2140.0493 2741.3674 3046.384  ... 2878.0642 2753.2449 2660.8215]
 [2921.3958 3045.3818 3323.1064 ... 1876.3672 3076.3965 3014.2886]]
(19200, 784)
(50000, 784)
(69200, 784)


 28%|██▊       | 25/88 [00:12<00:30,  2.10it/s]

[[2424.962  2483.1907 2820.857  ... 2326.353  2746.6335 2968.3623]
 [2500.03   2664.3547 3050.2063 ... 2860.0881 2761.9788 3125.237 ]
 [3160.3364 2652.505  2226.9783 ... 2642.251  2586.3848 3064.2314]
 ...
 [2954.9583 2415.5518 2657.88   ... 2489.7983 2492.5    2805.3857]
 [2997.2246 2331.2534 2994.04   ... 2198.1797 2516.0986 2862.233 ]
 [3029.8455 3047.4639 3192.4958 ... 2930.2993 2713.888  3147.0002]]
(20000, 784)
(49200, 784)
(69200, 784)


 30%|██▉       | 26/88 [00:12<00:29,  2.11it/s]

[[2435.4365 2827.1458 2761.77   ... 2171.1584 2485.4011 2438.846 ]
 [2433.8076 3199.776  2828.1277 ... 2614.3398 2826.4463 2544.8586]
 [2845.5173 2528.212  2760.3796 ... 2852.831  2793.0476 2422.79  ]
 ...
 [2658.995  2762.1104 1822.1158 ... 2872.5073 2774.3005 2334.0742]
 [3028.051  3084.8005 2187.6143 ... 2878.0889 2458.5188 2027.7996]
 [2873.1936 3045.8452 3187.1248 ... 3151.127  2626.2275 3129.787 ]]
(20800, 784)
(48400, 784)
(69200, 784)


 31%|███       | 27/88 [00:13<00:28,  2.12it/s]

[[2233.1802 2555.769  2383.9304 ... 2617.5017 2687.339  2431.5903]
 [2611.432  2238.4023 2715.6868 ... 2650.562  3212.5442 2835.1846]
 [2393.1665 2717.827  2411.6094 ... 2683.494  3024.3564 2482.6414]
 ...
 [2469.5696 2882.13   2465.4583 ... 2627.4902 2325.0166 2165.3203]
 [2551.6382 2531.6296 2283.472  ... 2839.678  2724.638  2495.0103]
 [3087.7551 2724.322  2917.0276 ... 2785.246  3203.929  2377.9104]]
(21600, 784)
(47600, 784)
(69200, 784)


 32%|███▏      | 28/88 [00:13<00:28,  2.13it/s]

[[2563.6836 2480.254  2462.4055 ... 2618.5488 2436.557  2509.02  ]
 [2009.2676 2603.8647 2214.8337 ... 3083.9963 2659.7056 2553.891 ]
 [2620.7595 2277.1738 2517.603  ... 3240.179  2291.7815 2540.9282]
 ...
 [2810.8206 2499.0105 2769.4326 ... 3074.1665 2429.392  1766.8514]
 [2764.9998 2430.2397 2606.0352 ... 2820.7246 2307.8127 2178.4558]
 [2709.7502 2848.445  2916.1792 ... 2874.8647 3021.7253 2987.7927]]
(22400, 784)
(46800, 784)
(69200, 784)


 33%|███▎      | 29/88 [00:13<00:27,  2.13it/s]

[[2426.8032 2556.8235 3137.9062 ... 2840.8965 2188.0776 2591.1304]
 [2682.7512 2566.0596 3230.4614 ... 2956.3574 2565.1436 2817.5176]
 [2503.8054 2530.1072 2620.0862 ... 2422.4937 2247.702  2368.6423]
 ...
 [1636.916  1913.0662 2535.9163 ... 2100.3103 2379.2188 1445.0443]
 [2148.099  2305.078  2825.3367 ... 2636.4067 2359.3982 2079.5251]
 [2895.9248 2971.7048 3315.143  ... 3214.755  2556.2976 2985.899 ]]
(23200, 784)
(46000, 784)
(69200, 784)


 34%|███▍      | 30/88 [00:14<00:27,  2.09it/s]

[[2359.2874 2837.0942 2679.83   ... 2200.3945 2426.1924 2972.343 ]
 [2457.8616 2840.7644 2559.3118 ... 2765.176  2639.18   3061.0442]
 [2554.5251 2544.4092 2649.2668 ... 2901.412  2471.2585 2258.6929]
 ...
 [2324.3848 1590.0786 2853.742  ... 2659.7117 1596.373  2639.0452]
 [2805.9004 2410.7415 2440.2466 ... 2888.7869 2229.7205 3028.476 ]
 [2924.013  2922.2922 2834.7717 ... 3184.783  2868.9558 3242.8997]]
(24000, 784)
(45200, 784)
(69200, 784)


 35%|███▌      | 31/88 [00:14<00:27,  2.11it/s]

[[2279.0222 2712.9146 2281.6885 ... 2508.173  3126.644  2068.8171]
 [2597.8044 2369.2556 2773.2515 ... 2840.6982 2420.8691 2468.961 ]
 [2854.7437 2914.7346 2634.744  ... 2910.604  3168.79   3011.2817]
 ...
 [2400.489  2397.1726 2484.538  ... 1971.3    3280.8232 2324.8547]
 [2521.5916 2388.067  2494.4214 ... 2514.7168 3215.9446 2468.2014]
 [2830.6172 3004.2893 2935.8777 ... 3254.1865 2679.207  3060.7366]]
(24800, 784)
(44400, 784)
(69200, 784)


 36%|███▋      | 32/88 [00:15<00:26,  2.11it/s]

[[2344.9033 2512.3464 2515.175  ... 2589.3022 2400.3726 2675.0745]
 [2729.718  2690.7888 2548.1453 ... 2739.6145 2691.209  2833.1995]
 [2443.191  2694.2532 2629.4375 ... 2666.8025 2296.3171 2676.0547]
 ...
 [2487.8787 2172.9248 2072.0493 ... 2408.1475 2415.5615 2319.5747]
 [2179.31   2466.5872 2241.5588 ... 2496.2668 2502.7961 2652.0557]
 [2916.4534 3213.1746 2420.934  ... 3123.2512 2941.2932 2129.7039]]
(25600, 784)
(43600, 784)
(69200, 784)


 38%|███▊      | 33/88 [00:15<00:26,  2.11it/s]

[[2318.7349 2406.1829 2690.0464 ... 2575.539  2679.762  2169.213 ]
 [2742.305  2543.5962 2887.1208 ... 2737.7678 2797.6802 2603.6855]
 [2531.4226 2811.6638 2308.8342 ... 2756.669  2894.8271 2487.1282]
 ...
 [2383.8027 2784.067  2197.4465 ... 1748.9529 2385.6475 2512.3477]
 [2159.4001 2716.4937 2655.361  ... 2549.3494 2780.4924 2332.5566]
 [2899.8184 3108.9497 3170.5645 ... 3037.4177 2291.715  3020.1233]]
(26400, 784)
(42800, 784)
(69200, 784)


 39%|███▊      | 34/88 [00:16<00:25,  2.11it/s]

[[2812.359  2357.7437 2674.4663 ... 3188.3186 2265.8235 2866.9434]
 [3145.0608 2598.3982 2761.5745 ... 3219.4153 2437.028  3014.5613]
 [2708.366  2387.2744 2491.7595 ... 3203.3171 2307.0557 2912.9614]
 ...
 [2586.149  2318.938  2472.7058 ... 2909.2786 2437.8245 2586.9495]
 [2902.9226 2331.2817 2714.3567 ... 3234.8035 2265.1433 2756.6956]
 [2996.2134 2986.8198 2557.1538 ... 3247.254  2455.6953 2932.195 ]]
235.99788
(27200, 784)
(42000, 784)
(69200, 784)


 40%|███▉      | 35/88 [00:16<00:25,  2.11it/s]

[[2883.141  2340.7583 2685.624  ... 2200.5938 2595.516  2521.2224]
 [2433.286  2784.817  2838.0422 ... 2535.45   3064.6143 2871.4668]
 [3263.979  2440.4731 2405.0251 ... 2915.6914 2781.4866 3051.828 ]
 ...
 [2946.8435 2512.213  2446.031  ... 2748.563  2592.3765 2313.1792]
 [3003.8196 2210.9841 2408.2712 ... 2643.1643 2724.0056 2654.1003]
 [2527.6174 2951.841  3231.2341 ... 2952.6716 2980.8555 3023.4526]]
(28000, 784)
(41200, 784)
(69200, 784)


 41%|████      | 36/88 [00:17<00:24,  2.12it/s]

[[2364.9414 2750.0298 2326.2146 ... 2640.2314 2363.7634 2552.0857]
 [2706.097  2970.9595 1365.0948 ... 2579.4783 2629.7021 2743.7617]
 [2461.7546 3039.2837 2679.5952 ... 2561.97   2361.2097 2343.9082]
 ...
 [2408.9226 2451.8923 2776.159  ... 2532.2078 2506.362  1648.1565]
 [2217.2764 2892.9714 2437.9275 ... 2776.0066 2571.007  2164.9438]
 [2875.5703 1922.7251 2487.722  ... 2308.5215 2537.6511 2941.6519]]
(28800, 784)
(40400, 784)
(69200, 784)


 42%|████▏     | 37/88 [00:17<00:24,  2.12it/s]

[[2673.722  2785.3967 2299.1274 ... 2483.863  2370.4143 2689.4475]
 [2981.0098 2721.16   2558.9673 ... 2594.7043 2627.027  1751.9663]
 [2430.913  2403.6804 2955.6416 ... 2393.7424 2325.926  2968.1277]
 ...
 [2464.4097 2678.3728 2540.2305 ... 2385.657  2427.2395 2990.8547]
 [2699.8594 2675.6912 2451.43   ... 2492.726  2242.5906 3025.089 ]
 [3130.7585 2826.992  3150.908  ... 2406.182  2902.2883 2676.4797]]
(29600, 784)
(39600, 784)
(69200, 784)


 43%|████▎     | 38/88 [00:18<00:23,  2.13it/s]

[[3051.815  2338.1816 2377.5732 ... 2466.7324 2397.8657 2954.9695]
 [2879.7314 2793.3384 2649.1357 ... 3034.8938 3061.9648 3110.9749]
 [2638.8853 2767.8904 2638.177  ... 2712.9885 2758.0845 2755.7883]
 ...
 [2677.2278 2398.593  2538.0872 ... 2593.5378 2773.9336 2833.587 ]
 [3173.1514 2651.0967 2230.097  ... 2701.6396 2893.2498 3042.9294]
 [2599.3745 3037.3416 2933.1458 ... 2965.1377 3115.4814 3187.5308]]
(30400, 784)
(38800, 784)
(69200, 784)


 44%|████▍     | 39/88 [00:18<00:23,  2.06it/s]

[[2671.9739 2764.8906 2445.5703 ... 2798.35   2302.9858 2364.0815]
 [3079.8103 3119.9895 2693.8372 ... 2861.306  2604.4895 1468.4753]
 [2691.764  2773.7378 2430.9949 ... 2171.8455 2611.7937 2688.525 ]
 ...
 [2752.5132 2350.52   2528.853  ... 2412.9043 2609.981  2708.926 ]
 [2666.1423 3004.6724 2972.216  ... 2412.0098 2428.843  2632.9736]
 [3254.7197 3205.1116 2866.7327 ... 2919.2275 2883.2205 2562.6924]]
(31200, 784)
(38000, 784)
(69200, 784)


 45%|████▌     | 40/88 [00:19<00:23,  2.07it/s]

[[2839.9968 2753.105  2756.9407 ... 2504.8079 2843.087  2080.9175]
 [2729.826  2833.9688 2487.7449 ... 2651.957  2695.2812 2401.3645]
 [2439.0251 2836.3022 2813.5056 ... 2728.814  2768.1238 2745.6106]
 ...
 [3084.9006 2878.9548 2955.5674 ... 1949.0505 2659.5352 2536.9036]
 [3058.2146 2942.3196 2988.382  ... 2399.0627 2993.9668 2322.9033]
 [3081.7942 3202.0522 2971.3225 ... 3135.7383 2172.9978 2769.18  ]]
(32000, 784)
(37200, 784)
(69200, 784)


 47%|████▋     | 41/88 [00:19<00:22,  2.08it/s]

[[2537.0815 1894.9116 2332.237  ... 2521.2256 2725.6091 2418.3164]
 [2581.3015 2464.9702 2796.3716 ... 2725.4468 2505.4375 2883.5503]
 [2451.5437 2941.3245 2430.9932 ... 2716.3303 1991.8933 2680.582 ]
 ...
 [2322.5405 2498.432  2489.9856 ... 2525.3977 2506.175  2704.8481]
 [2205.1846 2772.5837 2404.171  ... 2499.4827 2653.0056 2963.1958]
 [2913.0278 3104.2368 2768.733  ... 2841.7896 2539.189  3266.9597]]
(32800, 784)
(36400, 784)
(69200, 784)


 48%|████▊     | 42/88 [00:20<00:21,  2.10it/s]

[[2536.546  2765.3105 2474.299  ... 2481.9343 2669.9812 2509.2676]
 [1693.3862 2684.42   2820.6602 ... 2602.5344 2567.53   2725.9636]
 [2666.6956 2625.458  2310.5942 ... 2291.4673 2351.3718 2467.5493]
 ...
 [2850.9636 2153.285  2061.3977 ... 1840.0831 2660.3123 1767.4728]
 [2937.8616 2554.236  2483.251  ... 2370.634  2848.486  2479.8608]
 [2696.4253 2734.404  3048.746  ... 2964.3665 2869.9946 3048.8792]]
(33600, 784)
(35600, 784)
(69200, 784)


 49%|████▉     | 43/88 [00:20<00:21,  2.12it/s]

[[2501.663  2745.5269 2040.0245 ... 2757.9985 2599.7178 2306.8596]
 [2726.8447 2841.1724 2424.289  ... 3143.6885 3012.8438 2672.0952]
 [2661.8433 2718.0706 2867.2903 ... 2889.7087 2934.1768 2428.4087]
 ...
 [2467.8286 2930.1272 2739.9404 ... 2589.1848 2062.5981 2089.3823]
 [2267.4312 2951.6257 2895.7783 ... 2925.3696 2574.1948 2235.5132]
 [2916.3591 2467.2766 2876.9724 ... 3132.2046 3114.4949 3070.083 ]]
(34400, 784)
(34800, 784)
(69200, 784)


 50%|█████     | 44/88 [00:21<00:20,  2.11it/s]

[[2101.7988 2928.2695 2376.7048 ... 2362.4512 2668.9365 2574.4724]
 [2514.5476 2358.2954 2759.6133 ... 2662.1362 2545.2092 2672.9033]
 [2662.7065 3160.02   2656.5793 ... 2470.463  2356.8503 2621.8237]
 ...
 [2382.8777 3280.2139 2590.0637 ... 2446.767  2573.6511 1863.1044]
 [2779.1577 3081.6892 2286.0188 ... 2379.0505 2317.5703 2120.0127]
 [2794.7075 2733.2478 2786.3132 ... 3039.2366 2743.033  3069.27  ]]
(35200, 784)
(34000, 784)
(69200, 784)


 51%|█████     | 45/88 [00:21<00:20,  2.12it/s]

[[2824.8633 2642.3357 2588.7278 ... 2308.855  2169.4856 2248.3655]
 [2790.7793 2815.1018 2739.3484 ... 2603.2317 2650.4973 1890.1838]
 [2807.713  2361.7485 2765.8308 ... 2761.6858 2377.3289 2760.892 ]
 ...
 [2637.1226 1853.6796 2851.96   ... 2572.5737 2258.5876 2926.4858]
 [2929.5637 2137.0366 2430.6233 ... 2796.6204 2444.232  2528.4138]
 [2322.0393 2907.6245 2947.5664 ... 2905.0176 3019.6191 2707.793 ]]
(36000, 784)
(33200, 784)
(69200, 784)


 52%|█████▏    | 46/88 [00:22<00:19,  2.12it/s]

[[2656.0063 2873.901  2228.406  ... 3142.733  2541.0793 2717.1663]
 [2836.4897 2890.3867 2598.9558 ... 2509.9175 2650.8147 2656.7466]
 [2748.1914 2646.0264 2348.8477 ... 3788.0083 2549.2505 2908.6223]
 ...
 [1663.994  2713.0293 2564.6396 ... 3563.3618 2250.7153 2299.956 ]
 [2074.3655 2781.599  2335.8066 ... 3365.853  2539.9236 2628.3796]
 [3170.1797 2916.7554 2757.1548 ... 2966.0132 2625.643  3125.4756]]
(36800, 784)
(32400, 784)
(69200, 784)


 53%|█████▎    | 47/88 [00:22<00:19,  2.08it/s]

[[2782.9233 2639.6418 2568.3474 ... 2558.66   2381.2273 3072.3782]
 [2860.0144 2891.994  2584.303  ... 2916.899  2571.9683 3133.0593]
 [3011.3628 2862.8936 2598.321  ... 2484.0574 2301.4512 2810.1453]
 ...
 [2952.4343 2061.346  2834.7244 ... 2628.2263 2396.0554 2939.3035]
 [3137.371  2308.2502 2455.4597 ... 2794.657  2340.7192 2883.9512]
 [3096.238  3186.3755 2773.7815 ... 3091.1682 2983.7917 2998.35  ]]
(37600, 784)
(31600, 784)
(69200, 784)


 55%|█████▍    | 48/88 [00:23<00:19,  2.09it/s]

[[2498.0928 3107.762  2518.2334 ... 2604.8152 2409.6318 2652.7085]
 [2731.0918 2906.938  2887.311  ... 2692.5305 2760.5625 2873.7307]
 [2749.7354 3281.6619 2777.988  ... 2752.4817 2564.4697 3051.3213]
 ...
 [2167.3335 3336.7725 2108.2039 ... 2539.277  2442.844  2937.1646]
 [2540.103  3170.2783 2435.5642 ... 2303.8303 2197.2644 3013.4841]
 [2837.997  2703.6138 3033.7935 ... 3380.1553 2928.451  3398.0386]]
(38400, 784)
(30800, 784)
(69200, 784)


 56%|█████▌    | 49/88 [00:23<00:18,  2.11it/s]

[[2527.6262 2758.4521 2700.3599 ... 2748.0046 2304.5483 2494.6824]
 [2745.8901 2530.2234 2774.6885 ... 2703.8777 2900.0767 2698.    ]
 [2602.475  2604.2212 2040.0598 ... 2506.2913 3009.7683 2701.118 ]
 ...
 [2413.3264 2724.2886 2519.077  ... 2327.5862 2477.6758 1381.1328]
 [2698.8413 2494.0173 2716.1912 ... 1686.2799 2907.3652 2307.9744]
 [2312.1575 2972.1729 3031.7998 ... 3075.5825 2909.9573 2910.1326]]
(39200, 784)
(30000, 784)
(69200, 784)


 57%|█████▋    | 50/88 [00:23<00:17,  2.12it/s]

[[2779.962  2473.8948 2957.1467 ... 2866.1567 2803.154  2677.529 ]
 [2976.2378 2646.5322 2699.8435 ... 2715.5896 3188.1711 2730.3184]
 [2990.664  2996.1326 2898.9106 ... 2756.5234 2491.8425 2970.1135]
 ...
 [2521.7102 1919.1495 3177.0051 ... 2012.048  2602.4026 2818.3198]
 [3013.5244 2390.912  3064.483  ... 2487.5254 3002.0852 2648.8074]
 [2008.2739 2965.7744 3094.8848 ... 2902.2615 3246.0762 2724.9375]]
(40000, 784)
(29200, 784)
(69200, 784)


 58%|█████▊    | 51/88 [00:24<00:17,  2.13it/s]

[[2550.194  2621.9165 2423.6772 ... 2652.6348 2972.4265 2289.8552]
 [2722.0056 2522.5667 1428.3812 ... 2118.4634 2719.8962 2524.9976]
 [2733.771  2713.8179 2716.1309 ... 2974.4204 3015.3645 2543.65  ]
 ...
 [2003.2079 1740.6436 2795.2751 ... 3004.4006 2857.8171 1710.123 ]
 [2409.167  2335.7307 2671.957  ... 2447.5815 2795.8496 2368.468 ]
 [3150.014  2964.6963 2732.9514 ... 3032.0754 2555.1228 2987.0896]]
(40800, 784)
(28400, 784)
(69200, 784)


 59%|█████▉    | 52/88 [00:24<00:16,  2.13it/s]

[[2353.5225 2419.89   2327.2126 ... 2381.77   2317.5073 2644.2612]
 [2588.2542 1819.5018 2799.2559 ... 2497.7961 2680.7954 2530.8145]
 [2445.2766 2869.7231 2535.895  ... 2623.9128 2609.3953 2415.4292]
 ...
 [2237.484  3007.2754 2435.6775 ... 2201.3967 2275.8962 1747.9983]
 [2281.914  2552.9644 2182.792  ... 2484.2717 2612.5562 2276.3804]
 [3001.9814 2700.4941 2954.3672 ... 3075.2725 2822.1787 3051.3108]]
(41600, 784)
(27600, 784)
(69200, 784)


 60%|██████    | 53/88 [00:25<00:16,  2.14it/s]

[[2391.065  2634.5735 2763.7524 ... 3090.0923 2780.68   2908.4092]
 [2587.2068 2534.2844 3074.2705 ... 2891.8694 2982.2646 3029.256 ]
 [2432.9597 2642.1252 2597.8682 ... 3036.2795 2742.8804 2304.9187]
 ...
 [2379.0042 2136.6143 2872.1113 ... 2901.3582 2589.3105 2577.873 ]
 [2235.1477 2446.2454 3221.6765 ... 2804.2876 2840.87   2989.654 ]
 [2918.6724 3019.187  3172.0925 ... 3111.8274 3307.1123 2967.4348]]
(42400, 784)
(26800, 784)
(69200, 784)


 61%|██████▏   | 54/88 [00:25<00:15,  2.14it/s]

[[2449.3271 2416.4294 2845.7034 ... 2539.8352 2157.7202 2582.1353]
 [2587.6318 2730.384  2447.0632 ... 2683.317  2569.6057 2612.711 ]
 [2033.3735 2512.284  2605.4487 ... 2580.5168 2417.331  3107.4048]
 ...
 [2205.0425 2484.1174 2981.8533 ... 2514.9106 2443.6702 2834.5435]
 [2695.53   2225.5627 2803.5786 ... 2446.7036 2333.7793 3132.4365]
 [2672.387  2930.2595 2882.0212 ... 3072.0222 2945.3704 2819.4368]]
(43200, 784)
(26000, 784)
(69200, 784)


 62%|██████▎   | 55/88 [00:26<00:15,  2.10it/s]

[[2131.3508 2656.3108 2499.4922 ... 1828.2117 2993.606  2460.5647]
 [2615.7756 2708.537  2699.7556 ... 2416.4512 2894.205  2448.764 ]
 [2516.528  3046.0396 2490.6238 ... 2485.908  2494.7222 2341.2507]
 ...
 [2599.5447 2279.8655 2655.115  ... 2258.9246 2840.3425 2287.2134]
 [2603.7385 2620.6387 2749.3425 ... 2437.5566 2869.0867 2538.2551]
 [2836.3176 3079.332  3222.9167 ... 3117.489  3094.6655 2780.0703]]
(44000, 784)
(25200, 784)
(69200, 784)


 64%|██████▎   | 56/88 [00:26<00:15,  2.12it/s]

[[2787.5208 2658.979  2711.3782 ... 2370.3687 2577.2349 2110.791 ]
 [1891.6532 2575.2046 3040.4026 ... 2509.682  2698.0544 2504.903 ]
 [2782.293  2346.593  2593.4236 ... 2625.3167 2333.488  2627.2737]
 ...
 [2897.2312 2291.0322 2573.8245 ... 2443.0364 2064.4282 2532.2266]
 [2976.5356 2644.1572 2780.9197 ... 2505.0835 2485.6018 2536.8647]
 [2688.0405 2946.8552 3127.1313 ... 2825.3284 2697.9197 2910.5942]]
(44800, 784)
(24400, 784)
(69200, 784)


 65%|██████▍   | 57/88 [00:27<00:14,  2.14it/s]

[[2306.8855 2475.7576 1984.539  ... 2356.0588 2394.1428 2414.1064]
 [2707.9197 2808.1956 2486.0405 ... 2551.4692 2695.7737 2781.8462]
 [2489.524  2394.1917 2746.7563 ... 2739.367  2672.5486 2588.4702]
 ...
 [2528.0405 2154.7217 2312.6226 ... 2835.0825 2535.3823 2615.1907]
 [2323.695  2477.3247 2712.4504 ... 2822.6797 2193.7717 2822.3306]
 [2809.4941 2464.277  2744.3523 ... 2956.481  2880.962  3148.101 ]]
(45600, 784)
(23600, 784)
(69200, 784)


 66%|██████▌   | 58/88 [00:27<00:13,  2.15it/s]

[[2696.6626 2358.568  2940.1902 ... 2373.4712 2845.8198 2304.0693]
 [2820.9167 2596.7834 2774.1638 ... 2582.457  2357.869  2610.4878]
 [1986.8274 2696.8572 2766.3818 ... 2576.0999 2879.5242 2823.3027]
 ...
 [2623.2734 2813.5398 2519.0642 ... 2367.4028 3152.5984 2434.275 ]
 [2601.8423 2777.275  2569.3008 ... 2327.5159 3075.8508 2514.3015]
 [3131.1755 3067.9846 3169.3215 ... 2812.4666 2812.4858 2999.2605]]
(46400, 784)
(22800, 784)
(69200, 784)


 67%|██████▋   | 59/88 [00:28<00:13,  2.15it/s]

[[2772.5977 2539.6606 2682.9097 ... 2572.6943 2479.6694 2799.2888]
 [2684.6274 2656.9697 2967.2212 ... 1947.7197 2845.016  2397.4478]
 [2806.4119 2409.7498 2363.8787 ... 2917.8594 2225.2742 2628.9402]
 ...
 [2794.5818 1901.5746 1965.1183 ... 3037.2056 2392.6978 2850.6733]
 [2892.5706 2413.8765 2442.7905 ... 2767.9546 2573.8787 2707.5347]
 [2665.2947 2781.8171 3151.765  ... 2583.0586 3163.9749 2766.904 ]]
(47200, 784)
(22000, 784)
(69200, 784)


 68%|██████▊   | 60/88 [00:28<00:13,  2.15it/s]

[[2440.2795 2488.7927 2811.802  ... 2606.378  2346.8125 2819.586 ]
 [2751.6047 2626.1533 1714.4891 ... 1710.6917 2782.999  2612.2605]
 [2613.02   2808.5703 3305.5898 ... 2853.4456 2549.3096 2773.8643]
 ...
 [2467.9697 2252.3062 3210.041  ... 3009.7522 2538.6042 2986.096 ]
 [2302.1677 2137.5193 3084.217  ... 2589.376  2220.6917 3075.0198]
 [2932.1006 3001.9172 2444.1902 ... 2668.5674 2923.2542 2793.6836]]
(48000, 784)
(21200, 784)
(69200, 784)


 69%|██████▉   | 61/88 [00:29<00:12,  2.15it/s]

[[2513.014  2432.9912 2601.832  ... 2370.0132 2240.8906 2644.667 ]
 [2697.4785 2569.9207 2940.844  ... 2701.2043 2709.9194 2787.8823]
 [2398.1594 2837.901  2684.1692 ... 2735.2856 2599.659  2900.098 ]
 ...
 [2298.293  1797.5355 2629.5022 ... 2360.3206 2336.9436 2710.0225]
 [2519.8608 2376.2947 2818.475  ... 2205.2173 2265.0857 2791.5935]
 [2933.7253 3031.3499 3109.8032 ... 2808.2576 3109.2976 2363.851 ]]
(48800, 784)
(20400, 784)
(69200, 784)


 70%|███████   | 62/88 [00:29<00:12,  2.16it/s]

[[2219.3442 2476.884  2754.8787 ... 2555.519  2512.5876 2733.7969]
 [2482.5884 2788.3389 2437.43   ... 2498.413  2881.1768 2660.5115]
 [2634.779  2491.9116 2900.016  ... 2794.0906 2888.0098 2436.6816]
 ...
 [2457.5933 2724.6428 2707.0952 ... 2769.5754 2655.5469 2190.8682]
 [2229.391  2842.7893 2918.7307 ... 2448.418  2857.8342 2356.267 ]
 [2631.8335 3113.4272 3035.1511 ... 2428.7766 3007.2837 3024.0723]]
(49600, 784)
(19600, 784)
(69200, 784)


 72%|███████▏  | 63/88 [00:29<00:11,  2.15it/s]

[[2336.3796 2343.8582 2365.568  ... 2416.0542 2320.5708 1993.1207]
 [2929.5132 1695.3386 2828.9133 ... 2704.6804 2519.4985 2437.1858]
 [2755.5217 2774.9312 2778.489  ... 2664.9124 2927.6262 2673.8254]
 ...
 [2385.7715 2810.9954 2838.4995 ... 2318.3882 2371.1868 2569.5825]
 [2216.0059 2590.9248 2851.9685 ... 2270.3386 2478.3552 2239.1343]
 [2893.5508 2785.4963 3123.5964 ... 2956.1306 2732.5435 2612.7266]]
(50400, 784)
(18800, 784)
(69200, 784)


 73%|███████▎  | 64/88 [00:30<00:11,  2.12it/s]

[[2445.831  2179.0918 2297.3862 ... 2641.9626 2323.1558 2922.4077]
 [2649.8203 2678.8523 2588.0833 ... 2844.3472 2754.3076 2873.0615]
 [2473.8489 2683.9248 2203.2192 ... 2685.2703 2517.054  2748.53  ]
 ...
 [2362.2683 2495.2244 2478.0645 ... 2290.999  2052.8875 1991.0643]
 [2376.959  2353.7874 2431.758  ... 2410.7769 2357.1902 2826.9983]
 [3008.499  3256.1694 2653.704  ... 3188.3203 3127.181  2841.5645]]
(51200, 784)
(18000, 784)
(69200, 784)


 74%|███████▍  | 65/88 [00:30<00:10,  2.13it/s]

[[2326.6523 2402.1887 2672.0757 ... 2463.5134 2155.613  2528.9546]
 [2585.0369 2616.9512 2787.0823 ... 1245.6718 2549.9119 2428.7456]
 [2354.9006 2915.187  1630.0197 ... 2786.0916 2433.9478 2984.7285]
 ...
 [2239.538  2767.2075 2594.112  ... 2922.696  2404.035  3106.2307]
 [2125.0613 2565.304  2684.229  ... 2799.915  2252.3716 2887.973 ]
 [2849.8943 3000.6814 3110.4597 ... 2736.3345 3013.729  2773.8801]]
(52000, 784)
(17200, 784)
(69200, 784)


 75%|███████▌  | 66/88 [00:31<00:10,  2.14it/s]

[[2265.6335 2824.5947 2330.1995 ... 2359.1255 2624.8103 2304.3894]
 [2695.631  2944.7817 2725.2683 ... 2039.7281 2618.6433 1660.3352]
 [2223.7678 2699.4253 2289.047  ... 2614.0205 2641.9978 2784.4343]
 ...
 [2403.4229 2591.9963 2432.5461 ... 2511.5715 2649.447  2701.1792]
 [2397.8613 2747.381  2134.404  ... 2472.7708 2898.1667 2577.8606]
 [2716.027  2461.4285 2899.627  ... 2711.014  2924.0852 2679.3594]]
(52800, 784)
(16400, 784)
(69200, 784)


 76%|███████▌  | 67/88 [00:31<00:09,  2.14it/s]

[[2415.6824 2877.013  2472.3481 ... 2657.1277 3015.7886 2418.2268]
 [2916.1956 2982.5083 2828.7007 ... 2730.255  2919.1587 2635.3435]
 [2751.403  2635.4275 2496.498  ... 2544.8706 3025.1313 2574.3757]
 ...
 [2951.824  2740.7532 2522.2    ... 2001.383  3192.9446 2417.3752]
 [2769.952  2812.0251 2391.68   ... 2701.155  3193.0366 2375.6108]
 [2813.0056 3015.5369 2930.466  ... 3095.783  3269.739  2994.2068]]
(53600, 784)
(15600, 784)
(69200, 784)


 77%|███████▋  | 68/88 [00:32<00:09,  2.14it/s]

[[2240.7432 2527.895  2699.6846 ... 2718.6033 2506.221  2646.074 ]
 [2654.312  2621.6013 2967.0178 ... 2927.6377 2748.3982 2963.5664]
 [2623.1084 2280.5908 1980.8834 ... 3392.8154 2461.2004 2481.0122]
 ...
 [2232.9788 2381.6233 2440.9517 ... 3057.1514 2313.9692 2175.1216]
 [2467.842  2242.5007 2744.289  ... 3145.792  2453.4587 2711.7473]
 [2978.8257 3041.4312 3028.0723 ... 3333.1267 3064.2556 2979.1099]]
(54400, 784)
(14800, 784)
(69200, 784)


 78%|███████▊  | 69/88 [00:32<00:08,  2.16it/s]

[[2179.9753 2179.8806 2021.7476 ... 2648.8467 2036.4299 2445.4355]
 [2767.6953 2679.338  2675.4688 ... 2877.3977 2801.9094 2898.3608]
 [2972.6365 2920.1057 2655.283  ... 2434.1497 2761.5447 2852.5818]
 ...
 [2599.569  2565.9812 2336.947  ... 1508.6276 2600.6912 2701.89  ]
 [2714.05   2738.9731 2427.8713 ... 2337.2764 2569.7554 2784.5156]
 [2718.574  2661.3057 3014.6816 ... 3039.8289 3122.9016 2606.3716]]
(55200, 784)
(14000, 784)
(69200, 784)


 80%|███████▉  | 70/88 [00:33<00:08,  2.16it/s]

[[2701.0469 2711.2273 2308.3455 ... 3159.6296 2803.01   2630.501 ]
 [2840.6594 2785.5762 2883.0242 ... 2851.5981 2767.0032 2653.808 ]
 [2513.6348 2603.7769 2944.3623 ... 2811.6501 2933.2776 2928.028 ]
 ...
 [2388.6665 2223.8733 2499.4434 ... 3070.5964 2893.982  2596.8494]
 [2571.484  2412.7288 2607.741  ... 3094.7969 2758.0798 2757.5566]
 [2970.4316 2971.2917 2760.3865 ... 2478.0327 2804.231  2998.2588]]
(56000, 784)
(13200, 784)
(69200, 784)


 81%|████████  | 71/88 [00:33<00:07,  2.14it/s]

[[2445.8833 2524.004  2329.455  ... 2741.9023 2084.1807 2626.9626]
 [2671.909  2631.5105 2751.469  ... 3009.326  2639.8203 2882.3755]
 [2381.1523 2890.2295 2622.8323 ... 2570.6426 2659.9482 2543.5427]
 ...
 [2357.681  2550.7693 2602.3237 ... 2363.4841 2055.5244 1972.0134]
 [2390.138  2074.363  3047.2134 ... 2725.1619 2382.7961 2559.4387]
 [3110.8586 3073.0115 3081.68   ... 3101.528  2945.5247 3038.4001]]
(56800, 784)
(12400, 784)
(69200, 784)


 82%|████████▏ | 72/88 [00:34<00:07,  2.10it/s]

[[2287.5547 2922.3384 2934.8088 ... 2871.849  2535.7422 2479.5374]
 [2554.5544 2129.0037 2637.6602 ... 2759.0085 2585.7434 2696.6533]
 [2398.0308 3126.2935 2497.3303 ... 2464.2053 2566.8713 2530.0022]
 ...
 [2610.44   3262.7344 2681.5916 ... 2705.9023 2687.506  2376.0679]
 [2492.9607 3293.121  2783.5928 ... 2731.5374 2735.972  2433.2742]
 [2925.078  2900.2158 2402.4448 ... 2740.7156 2791.2583 3125.6272]]
(57600, 784)
(11600, 784)
(69200, 784)


 83%|████████▎ | 73/88 [00:34<00:07,  2.06it/s]

[[2424.805  2921.0674 2800.5972 ... 2425.0947 2792.8005 2076.713 ]
 [2749.153  2694.5981 2590.8862 ... 2637.273  2686.4417 2500.5544]
 [2703.6038 2900.4597 2621.953  ... 2831.6409 2949.5354 2937.182 ]
 ...
 [2146.285  2944.2905 2552.807  ... 2472.2334 2856.6233 2653.3281]
 [2520.1184 2496.3235 2384.2195 ... 2434.2312 2503.6914 2637.8853]
 [3180.319  3341.942  3117.2458 ... 3059.5598 2939.6313 3152.6064]]
(58400, 784)
(10800, 784)
(69200, 784)


 84%|████████▍ | 74/88 [00:35<00:06,  2.09it/s]

[[2732.2285 2701.889  2638.6982 ... 2359.2278 2308.1775 2501.193 ]
 [2780.3933 2798.7986 2367.277  ... 2360.413  2697.6921 2658.2883]
 [2273.6912 2428.4114 2809.526  ... 2694.105  2681.9077 2391.863 ]
 ...
 [2002.8008 2765.1099 2781.7522 ... 2457.9797 2062.135  2514.1077]
 [2366.8582 2976.1997 2873.972  ... 2609.4922 2405.2004 2424.374 ]
 [2851.2793 2711.4    2648.1995 ... 2405.2556 3129.636  3058.3608]]
(59200, 784)
(10000, 784)
(69200, 784)


 85%|████████▌ | 75/88 [00:35<00:06,  2.10it/s]

[[2430.9104 2367.836  2537.7566 ... 2009.2981 2478.9512 2530.6309]
 [2618.793  2310.7944 2588.1965 ... 2655.4565 2096.9746 2427.7876]
 [2379.5208 3024.1965 2735.9988 ... 2571.1067 2527.264  2425.4302]
 ...
 [2490.1094 2954.0732 2706.1135 ... 2546.6487 2629.3662 2473.064 ]
 [2378.57   2831.945  2819.657  ... 2653.6462 2317.0967 2357.3162]
 [3018.6423 2788.9214 2630.6704 ... 3091.0786 2062.938  2969.3606]]
(60000, 784)
(9200, 784)
(69200, 784)


 86%|████████▋ | 76/88 [00:36<00:05,  2.10it/s]

[[2395.7957 2851.6636 2352.0603 ... 2168.2566 2359.255  2996.2014]
 [2650.6304 2920.0146 2569.4521 ... 2528.6477 2858.3667 3151.673 ]
 [2407.3083 2972.5154 2334.0618 ... 2543.3677 2602.442  3084.7563]
 ...
 [2276.2766 3164.1638 2349.686  ... 2317.8062 2404.9167 3014.607 ]
 [2453.6458 2614.713  2271.6624 ... 2443.9426 2148.5864 2926.1567]
 [3174.72   3040.0715 2961.806  ... 2952.4873 2932.758  2929.7136]]
(60800, 784)
(8400, 784)
(69200, 784)


 88%|████████▊ | 77/88 [00:36<00:05,  2.06it/s]

[[2700.0022 2758.0974 2751.1042 ... 2403.0757 2178.3174 2782.6912]
 [2745.3777 2822.0146 2816.929  ... 2606.0757 2585.2314 2896.0881]
 [2722.7615 2950.2212 2102.9954 ... 2616.0415 3022.599  2306.9258]
 ...
 [2447.7444 2755.0605 2578.7896 ... 1816.8795 2738.046  2342.56  ]
 [2608.4988 2782.1836 2810.388  ... 2368.3013 2943.8625 2633.154 ]
 [2803.2395 2678.9028 3030.572  ... 2951.9697 3096.724  2939.633 ]]
(61600, 784)
(7600, 784)
(69200, 784)


 89%|████████▊ | 78/88 [00:37<00:04,  2.07it/s]

[[2202.304  2571.661  2359.3687 ... 2659.2478 2354.634  2399.8438]
 [2614.5896 2853.821  2865.5574 ... 2902.5918 2858.008  2800.5835]
 [2660.1868 2662.42   2506.86   ... 2565.8564 2803.2744 2659.743 ]
 ...
 [2649.6472 2418.6616 2118.2966 ... 2553.8928 2423.2446 2405.973 ]
 [2786.8977 2560.3843 2529.8625 ... 2825.6045 2213.6694 2665.5674]
 [2984.6887 3047.2322 2572.0461 ... 3142.5417 2836.8787 3197.8943]]
(62400, 784)
(6800, 784)
(69200, 784)


 90%|████████▉ | 79/88 [00:37<00:04,  2.09it/s]

[[2886.551  2802.128  2643.2927 ... 2574.9714 2940.2632 2373.73  ]
 [2990.2476 2795.6135 2925.6362 ... 2719.4353 3111.4492 2473.3264]
 [2697.2607 2481.511  2288.4062 ... 3021.2544 2796.633  2610.642 ]
 ...
 [2914.0808 2408.4744 2196.4167 ... 2217.8684 2725.4626 2503.5234]
 [2972.358  2748.0078 2613.228  ... 2375.0676 2617.1755 2950.7646]
 [3201.308  2941.5034 3070.7678 ... 2952.9097 3114.2698 2873.316 ]]
(63200, 784)
(6000, 784)
(69200, 784)


 91%|█████████ | 80/88 [00:38<00:03,  2.11it/s]

[[2841.8447 2710.085  2556.8525 ... 2446.24   2593.873  2703.017 ]
 [3104.215  2659.721  2879.333  ... 2639.1536 2689.6677 2891.3623]
 [2527.227  2742.8823 2459.8938 ... 2578.9016 2360.5557 2209.2065]
 ...
 [2725.069  2669.122  2047.081  ... 2530.1724 2511.6726 2477.0632]
 [3119.5137 2801.165  2388.5986 ... 2509.7454 2351.973  2974.08  ]
 [2883.5964 2304.8718 3124.2097 ... 3044.6428 2547.1538 3061.3062]]
(64000, 784)
(5200, 784)
(69200, 784)


 92%|█████████▏| 81/88 [00:38<00:03,  2.09it/s]

[[2810.9126 2741.854  2599.9114 ... 2636.177  2375.3557 2486.7173]
 [3157.8545 2667.4749 2503.3655 ... 2840.5452 2569.4724 2653.59  ]
 [2372.4192 2379.2952 3185.4358 ... 2767.804  2689.273  2503.2065]
 ...
 [2722.8145 2015.37   2602.8867 ... 2157.6875 2615.2283 2459.5427]
 [3043.0017 2549.7227 2329.8938 ... 2617.8354 2540.7178 2742.906 ]
 [3044.5107 2891.3904 3080.6875 ... 3055.9697 2581.266  2707.5208]]
(64800, 784)
(4400, 784)
(69200, 784)


 93%|█████████▎| 82/88 [00:39<00:02,  2.05it/s]

[[2394.5708 2758.7725 2395.505  ... 2734.7673 2680.7554 2602.7712]
 [2722.8499 2792.989  2794.2993 ... 2816.9375 2528.5334 2952.876 ]
 [2543.0947 2590.393  2252.0613 ... 2493.1055 2701.848  2496.5037]
 ...
 [2201.3667 2874.1377 2707.1401 ... 2302.1406 2420.3892 2416.634 ]
 [2436.712  2545.2693 2683.981  ... 2335.6777 2376.6968 2817.5588]
 [3147.0232 2828.2817 3010.1326 ... 2725.6167 3185.6333 2615.1697]]
(65600, 784)
(3600, 784)
(69200, 784)


 94%|█████████▍| 83/88 [00:39<00:02,  2.08it/s]

[[2358.9753 2678.6016 2507.567  ... 2401.3845 2408.0393 2693.7156]
 [2666.4297 2779.4414 2903.7449 ... 2683.297  2271.9832 2767.8555]
 [2771.3435 2657.9812 2742.0818 ... 2448.3416 2898.8586 2711.2139]
 ...
 [2165.7527 1881.755  2193.2283 ... 2411.8635 2686.8247 2484.631 ]
 [2254.694  2128.5762 2442.3306 ... 2154.189  2810.7961 2649.942 ]
 [2909.9954 2874.1062 3127.2268 ... 2932.844  2605.6914 2540.9333]]
(66400, 784)
(2800, 784)
(69200, 784)


 95%|█████████▌| 84/88 [00:40<00:01,  2.08it/s]

[[2540.681  2436.1028 2849.6267 ... 2584.669  2586.503  2544.1836]
 [2328.436  2707.7344 2608.182  ... 2389.9976 2410.9656 2720.1658]
 [2600.2927 2629.931  2876.8252 ... 2396.9163 2569.6963 2453.9421]
 ...
 [2332.8376 1973.8473 2388.2637 ... 2626.3887 2530.0164 2000.2765]
 [2445.2378 2406.9    2492.7117 ... 2552.2068 2473.4438 2553.8625]
 [2481.7869 2949.4656 2556.3567 ... 3067.789  3034.1438 3107.9312]]
(67200, 784)
(2000, 784)
(69200, 784)


 97%|█████████▋| 85/88 [00:40<00:01,  2.03it/s]

[[2443.7183 2477.6038 2601.579  ... 2643.1975 2730.6963 2917.999 ]
 [2496.0667 2815.6843 2442.8733 ... 2384.897  2837.1067 2679.8335]
 [2661.4734 2388.9119 2961.9568 ... 2834.497  2960.4993 3218.9197]
 ...
 [2377.9187 1593.9742 3125.0789 ... 2536.297  2530.7107 2343.171 ]
 [2519.2493 2244.4778 3156.4136 ... 1674.3037 2607.0808 2881.6787]
 [2853.47   2853.2964 3182.7253 ... 3032.6514 3123.057  2789.929 ]]
(68000, 784)
(1200, 784)
(69200, 784)


 98%|█████████▊| 86/88 [00:41<00:00,  2.02it/s]

[[3221.9336 2555.3787 2459.0815 ... 2674.2485 2876.0784 2398.718 ]
 [3051.8303 2796.5093 2782.27   ... 2795.2585 2142.5469 2611.1284]
 [2689.1724 2652.1138 2832.6772 ... 2515.6711 2968.373  2680.592 ]
 ...
 [2691.4338 2052.2715 1889.1294 ... 2132.012  3191.2192 2366.318 ]
 [2956.0476 2728.64   2217.9932 ... 2572.6165 3275.4878 2331.5356]
 [2860.6692 3008.2678 3141.327  ... 2962.1218 2915.926  3022.2866]]
(68800, 784)
(400, 784)
(69200, 784)


 99%|█████████▉| 87/88 [00:41<00:00,  1.97it/s]

[[3045.3628 2258.2468 2825.237  ... 3402.7776 2935.2542 2447.7578]
 [3065.8064 2619.0452 2743.6602 ... 3216.2217 2991.4863 2663.8381]
 [2923.2214 2856.0923 2465.8728 ... 2955.4585 3044.821  2804.1162]
 ...
 [2772.449  2683.7275 2408.175  ... 2959.1086 2763.4714 2500.3315]
 [3103.287  2671.9575 2763.9666 ... 3129.0303 3116.5444 2276.893 ]
 [2733.9185 3132.8867 2772.93   ... 2990.2852 2135.3174 2910.0354]]
(69600, 784)
(0, 784)
(69600, 784)


100%|██████████| 88/88 [00:41<00:00,  2.10it/s]

[[2778.4363 2482.493  2495.6829 ... 2627.5635 2693.4753 2944.14  ]
 [2572.7021 1804.0818 2696.1208 ... 2928.5857 2660.976  2512.646 ]
 [2557.5513 3089.0942 2542.9683 ... 2678.8157 2808.1008 3202.1177]
 ...
 [3065.4434 3168.0818 3046.2456 ... 2959.1086 3129.0303 2990.2852]
 [3034.885  2924.4248 3128.1345 ... 2763.4714 3116.5444 2135.3174]
 [2131.463  2931.3374 1280.2823 ... 2500.3315 2276.893  2910.0354]]
209.54951


In [ ]:
class Tree:
    def __init__(self):
        pass

    

In [3]:
sq1=np.sum(X*X,axis=1).reshape(-1,1)
sq2=np.sum(X.T*X.T,axis=1)
print(sq1)
print(sq2)
dist=X.T@X
distance_matrix=np.sqrt(sq1+sq2-2*dist)

[[5940005]
 [6750341]
 [3853933]
 ...
 [6602505]
 [5816711]
 [9416409]]
[         0          0          0          0          0          0
          0          0          0          0          0          0
      13556     111172      46656         81          0          0
          0          0          0          0          0          0
          0          0          0          0          0          0
          0          0        256       3717     122483     288365
     609724     736009    1627497    2258155    2566423    2436880
    2731668    2455656    2212721    1942690    1312113     948970
     644025     226558      88031      39034          0          0
          0          0          0          0       4096       1010
      39905      72798     658223    1734701    3558798    6753009
   12329050   18738953   26897411   35588935   45251376   49527387
   50702178   45774541   37112870   27546853   16116872    8314694
    3845215    1074158     375010      72932          0  

ValueError: operands could not be broadcast together with shapes (70000,784) (784,784) 

In [5]:
sq1=np.sum(X*X,axis=1).reshape(-1,1)
sq2=np.sum(X.T*X.T,axis=1)
dists=sq1+sq2- 2*np.dot(X,X.T)

MemoryError: Unable to allocate 36.5 GiB for an array with shape (70000, 70000) and data type int64

In [4]:
print(dist.shape)

(784, 784)
